Please fill out the information of your group!

| <p style="text-align: center;">First Name</p>  | <p style="text-align: center;">Family Name</p> | Matr.-No. |
| ---------------------------------------------- | ---------------------------------------------- | -------- |
| <p style="text-align: left">Boran Cihan</p>| <p style="text-align: left">Polat</p> | k12005254 |
| <p style="text-align: left">*EDIT!*</p>| <p style="text-align: left">*EDIT!*</p> | *EDIT!* |

<h2 style="text-align: center">344.105/6/7 UE: Natural Language Processing (WS2022/23)</h2>
<h1 style="color:rgb(0,120,170)">Assignment 1</h1>
<h2 style="color:rgb(0,120,170)">Document Classification with Standard Machine Learning Methods</h2>

<div style="background-color:rgb(224, 243, 255)">
<b>Terms of Use</b><br>
This  material is prepared for educational purposes at the Johannes Kepler University (JKU) Linz, and is exclusively provided to the registered students of the mentioned course at JKU. It is strictly forbidden to distribute the current file, the contents of the assignment, and its solution. The use or reproduction of this manuscript is only allowed for educational purposes in non-profit organizations, while in this case, the explicit prior acceptance of the author(s) is required.

**Authors:** Navid Rekab-saz, Oleg Lesota<br>

</div>

<h2>Table of contents</h2>
<ol>
    <a href="#section-general-guidelines"><li style="font-size:large;font-weight:bold">General Guidelines</li></a>
    <a href="#section-preprocessing"><li style="font-size:large;font-weight:bold">Task A: Pre-processing & Feature Extraction (15 points)</li></a>
    <a href="#section-training"><li style="font-size:large;font-weight:bold">Task B: Training and Results Analysis (15 points)</li></a>
    <a href="#section-optional"><li style="font-size:large;font-weight:bold">Task C: Linear Model Interpretability (2 extra point)</li></a>
    
</ol>

<a name="section-general-guidelines"></a><h2 style="color:rgb(0,120,170)">General Guidelines</h2>

<div style="background-color:rgb(224, 243, 255)">

### Assignment objective

The aim of this assignment is to implement a document (sentence) classification model using (standard) machine learning methods. The assignment in total has **30 points**; it also offers **2 extra points** which can cover any missing point.

This Notebook encompasses all aspects of the assignment, namely the descriptions of tasks as well as your solutions and reports. Feel free to add any required cell for solutions. The cells can contain code, reports, charts, tables, or any other material, required for the assignment. Feel free to provide the solutions in an interactive and visual way! 

Please discuss any unclear point in the assignment in the provided forum in MOODLE. It is also encouraged to provide answers to your peer's questions. However when submitting a post, keep in mind to avoid providing solutions. Please let the tutor(s) know shall you find any error or unclarity in the assignment.

</div>

<div style="background-color:rgb(224, 243, 255)">

### Libraries & Dataset

The assignment should be implemented with recent versions of `Python` (>3.7). Any standard Python library can be used, so far that the library is free and can be simply installed using `pip` or `conda`. Examples of potentially useful libraries are `scikit-learn`, `numpy`, `scipy`, `gensim`, `nltk`, `spaCy`, and `AllenNLP`. Use the latest stable version of each library.

To conduct the experiments, we use a subset of the `HumSet` dataset [1] (https://blog.thedeep.io/humset/). `HumSet` is created by the DEEP (https://www.thedeep.io) project – an open source platform which aims to facilitate processing of textual data for international humanitarian response organizations. The platform enables the classification of text excerpts, extracted from news and reports into a set of domain specific classes. The provided dataset contains the classes (labels) referring to the humanitarian sectors like agriculture, health, and protection. The dataset contains an overall number of 17,301 data points. 

Download the dataset from the Moodle page of the course.

the provided zip file consists of the following files:
- `thedeep.subset.train.txt`: Train set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.validation.txt`: Validation set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.test.txt`: Test set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.labels.txt`: Captions of the labels.
- `thedeep.ToU.txt`: Terms of use of the dataset.

[1] HumSet: Dataset of Multilingual Information Extraction and Classification for Humanitarian Crises Response
*Selim Fekih, Nicolo' Tamagnone, Benjamin Minixhofer, Ranjan Shrestha, Ximena Contla, Ewan Oglethorpe and Navid Rekabsaz.* 
In Findings of the 2022 Conference on Empirical Methods in Natural Language Processing (Findings of EMNLP), December 2022.

</div>

<div style="background-color:rgb(224, 243, 255)">

### Submission

Each group should submit the following two files:

- One Jupyter Notebook file (`.ipynb`), containing all the code, results, visualizations, etc. **In the submitted Notebook, all the results and visualizations should already be present, and can be observed simply by loading the Notebook in a browser.** The Notebook must be self-contained, meaning that (if necessary) one can run all the cells from top to bottom without any error. Do not forget to put in your names and student numbers in the first cell of the Notebook. 
- The HTML file (`.html`) achieved from exporting the Jupyter Notebook to HTML (Download As HTML).

You do not need to include the data files in the submission.


</div>

<a name="section-preprocessing"></a><h2 style="color:rgb(0,120,170)">Task A: Pre-processing & Feature Extraction (15 points)</h2>

<div style="background-color:rgb(224, 243, 255)">
    
**Preprocessing (5 points).** Load the train, validation, and test sets. Study the text and according to your judgements, apply at least <ins>two text cleaning/preprocessing methods</ins>. Punctuations marks, numbers, dates, case-sensitivity are some examples of the elements which can be potentially considered for cleaning/preprocessing. Tokenize the result text with a tokenizer of your choice. Report your approaches to text cleaning and tokenization and the reasons of your choices. Provide some examples, showing the effects of the applied approaches on the text.

**Creating dictionary (5 points).** Create a dictionary of vocabularies following the guidelines discussed in the lecture. Next, reduce the size of dictionary using a method of your choice, for instance by considering a cut-off threshold on the tokens with low frequencies. When removing tokens from the dictionary, consider a strategy for handling Out-Of-Vocabulary (OOV) tokens, namely the ones in the train/validation/test datasets that that are not anymore in the dictionary. Some possible strategies could be to remove OOVs completely from the texts, or to replace them with a special token like <OOV\>. Explain your approaches and report the statistics of the dictionary before and after the reduction.

**Creating sentence vectors (5 points).** Use the dictionary to prepare <ins>two variations of document representation vectors</ins>, separately for train, validation, and test sets. Both variations follow a Bag-of-Words approach with a different token weighting method. One applied weighting must be `tf-idf` and the other one can be any other method discussed in the lecture such as `tc`, `tf`, `BM25`. These term weighting methods should be implemented; using a library to readily calculate the term weightings is not allowed. Report the applied approaches. Calculate and report the sparsity rate of the vectors of train, validation, and test sets, namely what percentages of the vectors in each set are filled with zeros.

</div>

<h2>Used Libraries</h2>

In [1]:
import pandas as pd
import re
import nltk
from collections import Counter
import heapq
import numpy as np
import itertools

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Boran\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Boran\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Boran\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

<h2>Preprocessing</h2>

<h3>Load Data</h3>

In [2]:
train_text = pd.read_csv("nlp2023_24_data/thedeep.subset.train.txt", header=None, names=["Number", "Text", "Label"])
validation_text = pd.read_csv("nlp2023_24_data/thedeep.subset.validation.txt", header=None, names=["Number", "Text", "Label"])
test_text = pd.read_csv("nlp2023_24_data/thedeep.subset.test.txt", header=None, names=["Number", "Text", "Label"])
train_text.head()

   Number                                               Text  Label
0    5446  In addition to the immediate life-saving inter...      9
1    8812  There are approximately 2.6 million people cla...      3
2   16709  While aid imports have held up recently, comme...      5
3    3526  Heavy rainfalls as well as onrush of water fro...      0
4    4928  Based on field reports 9 , the main production...      3

<h3>Cleaning Raw Data</h3>

In [3]:
# Stopwords are commonly occurring words in a language like ‘the’, ‘a’, and so on.
# They can be removed from the text most of the time, as they don’t provide valuable information.
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

print(f"Before Cleaning Raw Data (aka. Preprocessing):\n {train_text.Text[0]}")
def preprocessing(text: pd.Series):
    clean_text =[]
    # text.str.lower = Lowering each word of text in all columns
    for sentence in text.str.lower():
        # replaces special symbols @ # $ §, etc. with " "
        sentence = (re.sub('[^A-Za-z0-9]+', ' ', sentence))
        
        # Regular expression pattern for dates in the format yyyy-mm-dd
        date_pattern = r'\d{4}-\d{2}-\d{2}'
        # Regular expression pattern for numbers with optional decimal points
        number_pattern = r'\d+(\.\d+)?'
        sentence = (re.sub(date_pattern, "<dates>", sentence))
        sentence = (re.sub(number_pattern, "<num>", sentence))
        
        # Words like ‘the’, ‘to’, ‘at’ are removed
        sentence = ' '.join(e.lower() for e in sentence.split() if e.lower() not in stopwords)
        
        #Removal any URLs and HTML tags
        sentence = re.sub(r"http\S+", "", sentence)
        sentence = re.sub(r"'<.*?>'", "", sentence)
    
        clean_text.append(sentence)
    return clean_text

Before Cleaning Raw Data (aka. Preprocessing):
 In addition to the immediate life-saving interventions, UNICEF is taking action to protect 200 children who have arrived at the camps in Angola without their families.

In [4]:
train_text.Text = preprocessing(train_text.Text)
validation_text.Text = preprocessing(validation_text.Text)
test_text.Text = preprocessing(test_text.Text)
print(f"After Cleaning Raw Data (aka. Preprocessing):\n {train_text.Text[0]}")

After Cleaning Raw Data (aka. Preprocessing):
 addition immediate life saving interventions unicef taking action protect <num> children arrived camps angola without families

In [5]:
train_text.head()

   Number                                               Text  Label
0    5446  addition immediate life saving interventions u...      9
1    8812  approximately <num> <num> million people class...      3
2   16709  aid imports held recently commercial food fuel...      5
3    3526  heavy rainfalls well onrush water upstream meg...      0
4    4928  based field reports <num> main production chal...      3

<h3>Tokenization</h3>

<h4>Porter’s stemmer & Lemmatization functions </h4>

In [6]:
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

# Porter’s stemmer 
# A stemmer reduces words to their “stems” by crude affix chopping
# automate, automates, automatic, automation -> automat
def stem_words(list_of_tokens: []):
    ps = PorterStemmer()
    
    stem_words = []
    for word in list_of_tokens:
        if word != "<num>" or word != "<dates>":
            stem_words.append(ps.stem(word))
        else:
            stem_words.append(word)
    return stem_words

# Lemmatization
# lemmatizer uses a knowledge resource (like WordNet) to find and replace base forms
# stemming ist faster, but also harms precision and increase ambiguity, therefore we choose Lemmatization
def lem_words(list_of_tokens: []):
    lemmatizer = WordNetLemmatizer()
    lem_words = []
    for word in list_of_tokens:
        if word != "<num>" or word != "<dates>":
            lem_words.append(lemmatizer.lemmatize(word))
        else:
            lem_words.append(word)
            
    return lem_words

<h4>Tokenize data</h4>

In [7]:
def tokenization(text: pd.Series, normalization_method: str = "lem"):
    list_of_words = []
    for sentence in text:
        # not using word_tokenize, because i want to have "<num>" and not "<","num", ">"
        list_of_words.append(sentence.split())
        
    # gets normalized with one of the methods
    # default method is lem_words
    if normalization_method == "lem":
        return lem_words(np.concatenate(list_of_words)), list_of_words
    else:
        return stem_words(np.concatenate(list_of_words)), list_of_words

In [8]:
train_tokens, train_corpus = tokenization(train_text.Text)
validation_tokens, validation_corpus = tokenization(validation_text.Text)
test_tokens, test_corpus = tokenization(test_text.Text)
print(f"First 50 tokens of training_text:\n{train_tokens[0:50]}")

First 50 tokens of training_text:
['addition', 'immediate', 'life', 'saving', 'intervention', 'unicef', 'taking', 'action', 'protect', '<num>', 'child', 'arrived', 'camp', 'angola', 'without', 'family', 'approximately', '<num>', '<num>', 'million', 'people', 'classified', 'phase', '<num>', '<num>', 'million', 'already', 'emergency', 'ipc', 'phase', '<num>', 'meet', 'threshold', '<num>', 'percent', 'population', 'phase', 'area', 'classified', 'phase', '<num>', 'county', 'classified', 'crisis', 'ipc', 'phase', '<num>', 'turkana', 'marsabit', 'west']

<h2>Creating dictionary</h2>

In [9]:
# Counter counts all words + each frequency
dictionary_of_all_words = Counter(train_tokens)

# threshold is 80 % of bag of words
threshold = int(len(dictionary_of_all_words) * 0.8)
dictionary_with_threshold = heapq.nlargest(threshold, dictionary_of_all_words, key=dictionary_of_all_words.get)

# creating list of unique tokens of train_tokens
used = set()
unique_train_tokens = [x for x in train_tokens if x not in used and (used.add(x) or True)]

# OOV
out_of_vocabulary = list(set(unique_train_tokens) - set(dictionary_with_threshold))

<h3>Handeling OOVs</h3>

<h4>Replacing OOV-words in train/val/test</h4>

In [10]:
def replacing_OOV(text: pd.Series, oovs: []):
    senteces_without_oov = []
    for sentence in text:
        sentence = np.asarray(sentence.split())

        # get indeces of OOV words in looped sentence
        oov_words_position_in_sentence = np.where(np.isin(sentence, oovs))[0]

        # if no OOV words are included in sentece skip sentence
        if len(oov_words_position_in_sentence) == 0:
            # sentence to string again
            sentence = " ".join(sentence)
            senteces_without_oov.append(sentence)
        else:
            # make regex pattern with the OVV words in sentence
            pattern = r"|".join(sentence[oov_words_position_in_sentence])
            # sentence to string again
            sentence = " ".join(sentence)
            # replace OOV word with "OOV"
            sentence = (re.sub(pattern, "<oov>", sentence))
            senteces_without_oov.append(sentence)
    return senteces_without_oov

In [11]:
train_text.Text = replacing_OOV(text=train_text.Text, oovs=out_of_vocabulary)
validation_text.Text = replacing_OOV(text=validation_text.Text, oovs=out_of_vocabulary)
test_text.Text = replacing_OOV(text=test_text.Text, oovs=out_of_vocabulary)

<h2>Creating sentence vectors</h2>

In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Create a CountVectorizer for Term Count (TC)
count_vectorizer = CountVectorizer()
count_train_vectors = count_vectorizer.fit_transform(train_text.Text)
count_validation_vectors = count_vectorizer.transform(validation_text.Text)
count_test_vectors = count_vectorizer.transform(test_text.Text)

# Create a TfidfVectorizer for TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf_train_vectors = tfidf_vectorizer.fit_transform(train_text.Text)
tfidf_validation_vectors = tfidf_vectorizer.transform(validation_text.Text)
tfidf_test_vectors = tfidf_vectorizer.transform(test_text.Text)

In [13]:
# Calculate sparsity rate for each set
def calculate_sparsity_rate(vector):
    total_elements = vector.shape[0] * vector.shape[1]
    zero_elements = total_elements - vector.count_nonzero()
    sparsity_rate = (zero_elements / total_elements) * 100
    return sparsity_rate

sparsity_rate_train_count = calculate_sparsity_rate(count_train_vectors)
sparsity_rate_validation_count = calculate_sparsity_rate(count_validation_vectors)
sparsity_rate_test_count = calculate_sparsity_rate(count_test_vectors)

sparsity_rate_train_tfidf = calculate_sparsity_rate(tfidf_train_vectors)
sparsity_rate_validation_tfidf = calculate_sparsity_rate(tfidf_validation_vectors)
sparsity_rate_test_tfidf = calculate_sparsity_rate(tfidf_test_vectors)

# Report the approaches and sparsity rates
print("Term Count (TC) Approach:")
print(f"Train Set Sparsity Rate: {sparsity_rate_train_count:.2f}%")
print(f"Validation Set Sparsity Rate: {sparsity_rate_validation_count:.2f}%")
print(f"Test Set Sparsity Rate: {sparsity_rate_test_count:.2f}%")

print("\nTF-IDF Approach:")
print(f"Train Set Sparsity Rate: {sparsity_rate_train_tfidf:.2f}%")
print(f"Validation Set Sparsity Rate: {sparsity_rate_validation_tfidf:.2f}%")
print(f"Test Set Sparsity Rate: {sparsity_rate_test_tfidf:.2f}%")

Term Count (TC) Approach:
Train Set Sparsity Rate: 99.84%
Validation Set Sparsity Rate: 99.84%
Test Set Sparsity Rate: 99.84%

TF-IDF Approach:
Train Set Sparsity Rate: 99.84%
Validation Set Sparsity Rate: 99.84%
Test Set Sparsity Rate: 99.84%

<a name="section-training"></a><h2 style="color:rgb(0,120,170)">Task B: Training and Results Analysis (15 points)</h2>

<div style="background-color:rgb(224, 243, 255)">

To evaluate the models, use <ins>accuracy</ins> as the metric throughout the task. 

**Dummy baseline (2 points).** Create one dummy baseline classifier that predicts the validation/test labels only based on the distribution of the labels in the training set (without any use of the feature vectors). This is a weak baseline and acts as a sanity check for the actual classifiers.

**Training and tuning classifiers (5 points).** Select at least <ins>two classification algorithms</ins> from standard machine learning classifiers. Using each classification algorithm, train a machine learning model on each of the variations of feature vectors. This should result in <ins>four experiment sets</ins> (2 variations of feature vectors × 2 classification algorithms). The ML model in each of the experiments possibly have several involving hyper-parameters. For each experiment, select <ins>one of the hyper-parameters and tune its value</ins>. The tuning process is done by first assigning at least <ins>three values</ins> to the hyper-parameter, then training separate models based on each value, and finally using the evaluation results on the validation set to select the best-performing model. Report the studied hyper-parameters, the evaluation results of each on validation set, and finally the selected value of the hyper-parameter. 

**Evaluation, reporting results, and discussion (3 point).** Evaluate the selected models of the four experiments on the test set. Report the results of <ins>the four experiments on both validation and test sets (side by side) in one table as well as in one plot</ins>. Compare different experiments and models. Are the test results lower(/higher) than the validation results? If it is the case, where can it be rooted from? Among all these models and variations, what are the most important factors improving the classification results?

**Confusion matrix (2 point).** Select the best performing model among the experiments and use it to create a confusion matrix. The matrix shows the predicted versus true results per each label. Explain your observations on the matrix. Across which classes do you observe significant confusions?

**Features visualization (3 point).** Continue with the best performing model and now take its feature vectors for the *dataitems in the test set*. Project these feature vectors to a 2-dimensional space using the TSNE method.  Using these 2-dimensional vectors, create two plots where the dataitems are shown as points (small circles) on the plots. The plots look exactly the same but only differ in the coloring of the data points. The first plot colors every dataitem with its *true label*, while the second one colors each according to its *predicted label by the model*. Keep in mind to assign the same colors to the classes of the plots, so that the plots are visually comparable. Put these two plots side by side, observe the differences, and compare the results. Report your observations.


</div>

<a name="section-optional"></a><h2 style="color:rgb(0,120,170)">Task C: Linear Model Interpretability (2 extra points)</h2>

<div style="background-color:rgb(224, 243, 255)">
Train a logistic regression model on one of the document representations. Take the coefficient weights, learned by the model, on each dimension (which here corresponds to each token in the dictionary). Separately for each class, study what are the tokens that have the highest contributions/importance for the predictions of the model.
</div>